<a href="https://colab.research.google.com/github/dineshssdn-867/Python_collab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [3]:
import numpy as np
import sys


# Initializing values to numpy array

In [47]:
a= np.array([1, 5, 6], dtype='int64')
print(a)

[1 5 6]


In [ ]:
b = np.array([[1.0, 2.0], [3.0, 4.0]])
print(b)

[[1. 2.]
 [3. 4.]]


# Getting the Sizes of array

In [50]:
print("Dimension of a is "+str(a.ndim))

Dimension of a is 4


In [56]:
print("Shape of a is "+str(a.shape))

Shape of a is (2, 6)


In [8]:
print(a.dtype)

int16


In [11]:
a.itemsize

8

In [13]:
a.nbytes

24

In [55]:
a= np.array([[1, 2, 3, 4, 5, 6,],[7, 8, 9, 10, 11, 12]], dtype='int64')

In [15]:
a.shape

(2, 6)

In [17]:
a[0,2]

3

In [18]:
a[0]

array([1, 2, 3, 4, 5, 6])

In [19]:
a[:,0]

array([1, 7])

In [22]:
a[:2,:6]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
a[0, 1:6:2]

array([2, 4, 6])

In [24]:
a[1:5]=9

In [25]:
a

array([[1, 2, 3, 4, 5, 6],
       [9, 9, 9, 9, 9, 9]])

In [30]:
b=np.array([[[1,2],[1,3]], [[4,5], [7,9]]])
print(b)

[[[1 2]
  [1 3]]

 [[4 5]
  [7 9]]]


In [34]:
b[0,1,1]
b[:,1,:]

array([[1, 3],
       [7, 9]])

# Intialize zeroes and ones array

In [40]:
a = np.zeros([6,6])
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
a = np.ones([10,6,6,6])
a.size

2160

In [58]:
np.full_like(a.shape,4)

array([4, 4])

In [62]:
np.random.rand(2,4,8)

array([[[0.99523839, 0.82731964, 0.33196508, 0.28445611, 0.61176011,
         0.27381038, 0.38792586, 0.34187439],
        [0.88748582, 0.4152835 , 0.10483995, 0.84548194, 0.53174018,
         0.56276714, 0.05314431, 0.74508151],
        [0.65848806, 0.43743314, 0.36314997, 0.73194161, 0.36547129,
         0.82390323, 0.6662788 , 0.96564212],
        [0.8891684 , 0.88693071, 0.2719308 , 0.79430328, 0.18116511,
         0.5416001 , 0.05126635, 0.51869951]],

       [[0.10764576, 0.96275043, 0.6755349 , 0.62809524, 0.75973345,
         0.22544295, 0.91672631, 0.01831314],
        [0.46564702, 0.62389186, 0.36812104, 0.00711355, 0.28836497,
         0.36107708, 0.52343754, 0.26516881],
        [0.47841731, 0.66047098, 0.90606016, 0.10270215, 0.82142625,
         0.28107944, 0.990297  , 0.21271657],
        [0.7312784 , 0.62799801, 0.94539559, 0.30153136, 0.91294768,
         0.06417447, 0.58683509, 0.69402665]]])

In [67]:
np.random.random_sample(a.shape)

array([[0.21071525, 0.27712609, 0.7161812 , 0.11945397, 0.92031186,
        0.59252069],
       [0.82238427, 0.82487144, 0.91655323, 0.116066  , 0.37629315,
        0.76774097]])

In [70]:
np.random.randint(7, size=(1,4))

array([[4, 4, 1, 4]])

In [72]:
np.identity(8, dtype="int8")

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [75]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [109]:
n = int(input("Please enter only odd Number: "))
mid=int((n-1)/2)
print(mid)
a = np.zeros((n,n), dtype='int16')
a[0,:]=1
a[:,0]=1
a[n-1,:]=1
a[mid,mid]=9
a[:,n-1]=1
a

Please enter only odd Number: 9
4


array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 9, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [104]:
a = np.full((2,3),9)
a
b = np.full((3,2), 2)
c = np.matmul(a,b)
c

array([[54, 54],
       [54, 54]])

In [108]:
c = np.identity(3)
c = np.linalg.det(c)
c

1.0

In [ ]:

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Reorganize array

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)


# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


# Miscellaneous

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)
(~((filedata > 50) & (filedata < 100)))